# Generated by Django 5.1.3 on 2024-12-12 17:33

import cloudinary.models
import django.utils.timezone
import eventsProject.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='user_bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='user_name',
            new_name='display_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_picture',
        ),
        migrations.AddField(
            model_name='basecustomuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[eventsProject.utils.validators.ImageFileValidator()], verbose_name='image'),
        ),
    ]
